apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-sandbox
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nkzren/k8s-sandbox.git
    targetRevision: HEAD
    path: ./argocd/bootstrap/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
